Add a hook for ``pingouin`` to collect data files.
pyinstaller/pyinstaller-hooks-contrib pull request #292
Opened 2021-08-17 21:19 UTC by JonMrowczynski

2021-08-18 07:54 UTC, bwoodsend commented
Are users really likely to need those files? The csv files look like test/example datasets (although they are pretty tiny so they don't waste much space if they're not needed).

2021-08-18 14:56 UTC, JonMrowczynski commented
Hello Brénainn,

Thank you very much for your response.hi

The reason for adding those files was due to at least pingouin's need for them. When I attempted to create either a onedir or a onefile executable using PyInstaller for a Python script using pingouin, it would fail when the executable was run. When my script imports pingouin, a FileNotFoundError would be thrown because pingouin would try to load dataset.csv...which wouldn't get packaged without the hook.

Adding this hook was the only way I was able to get my script to run as an executable when implementing pingouin. Kind of like what was recommended here: https://groups.google.com/g/pyinstaller/c/OYhJdeZ9010

Let me know if that answers your question or if I could offer any additional information. Thanks! :)
________________________________
From: Brénainn Woodsend ***@***.***>
Sent: Wednesday, August 18, 2021 3:54:16 AM
To: pyinstaller/pyinstaller-hooks-contrib ***@***.***>
Cc: Jon Mrowczynski ***@***.***>; Author ***@***.***>
Subject: Re: [pyinstaller/pyinstaller-hooks-contrib] Add a hook for ``pingouin`` to collect data files. (#292)


Are users really likely to need those files? The csv files look like test/example datasets (although they are pretty tiny so they don't waste much space if they're not needed).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/292#issuecomment-900900770>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJKA5JLQWOIC3UNI3RMO6FTT5NRKRANCNFSM5CKWFFMA>.

2021-08-18 16:23 UTC, bwoodsend commented
I've tried it out and it looks like only the `pingouin/datasets/datasets.csv` file is needed but it's much easier just to collect everything like you already are so I'll accept this for now. Can you give us [a test](https://github.com/bwoodsend/pyinstaller-hooks-contrib/tree/readme#write-tests) and [add pingouin to the requirements file](https://github.com/bwoodsend/pyinstaller-hooks-contrib/tree/readme#pin-the-test-requirement)?

2021-08-19 01:19 UTC, JonMrowczynski commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Hello again Brénainn, That’s what I was thinking as well. Thank you very much for taking a look at that. I just added a test and pingouin to the requirements file. I also pushed those changes to my master branch. Let me know if you need anything else from me. Thanks again. From: Brénainn WoodsendSent: Wednesday, August 18, 2021 12:24To: pyinstaller/pyinstaller-hooks-contribCc: Jon Mrowczynski; AuthorSubject: Re: [pyinstaller/pyinstaller-hooks-contrib] Add a hook for ``pingouin`` to collect data files. (#292) I've tried it out and it looks like only the pingouin/datasets/datasets.csv file is needed but it's much easier just to collect everything like you already are so I'll accept this for now. Can you give us a test and add pingouin to the requirements file?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-08-19 13:49 UTC, bwoodsend approved these changes

2021-08-19 13:51 UTC, bwoodsend requested changes

2021-08-19 13:51 UTC, bwoodsend commented on src/_pyinstaller_hooks_contrib/tests/test_libraries.py
> +
Ugh damm, the linter wants an extra blank line here.
```suggestion


```

2021-08-19 13:52 UTC, merged

2021-08-19 13:52 UTC, bwoodsend commented
Thanks @JonMrowczynski!

2021-08-19 14:45 UTC, JonMrowczynski commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->No problem, thank you! 😊 From: Brénainn WoodsendSent: Thursday, August 19, 2021 9:52To: pyinstaller/pyinstaller-hooks-contribCc: Jon Mrowczynski; MentionSubject: Re: [pyinstaller/pyinstaller-hooks-contrib] Add a hook for ``pingouin`` to collect data files. (#292) Thanks @JonMrowczynski!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 