Add email_validator to the list of pydantic optional dependencies hidden imports
pyinstaller/pyinstaller-hooks-contrib pull request #576
Opened 2023-05-01 00:30 UTC by pjrm

This commit adds the missing email-validator package required by Pydantic when validating email.

Without it, we have to manually append the package `email_validator` on the hidden-import argument.

You can find more information about this change in the documentation at https://docs.pydantic.dev/latest/install/#optional-dependencies .

2023-05-01 21:11 UTC, bwoodsend requested changes
Just need a [news entry](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/0f5685dc82b7be77de6ae1cd4e847af57a82e1bc/news/README.txt).

2023-05-01 22:34 UTC, pjrm commented
Thanks, @bwoodsend! I've made the requested updates to the PR. Please let me know if there's anything else needed.

2023-05-01 22:40 UTC, rokm approved these changes

2023-05-02 07:39 UTC, merged

2023-05-02 07:40 UTC, bwoodsend commented
Thanks Pedro!