Add CtkMessagebox hook.
pyinstaller/pyinstaller-hooks-contrib pull request #619
Opened 2023-07-29 14:48 UTC by pcroland

2023-07-29 15:06 UTC, bwoodsend requested changes
We need a news entry, and preferably a test. See [the readme](https://github.com/pyinstaller/pyinstaller-hooks-contrib#summary).

2023-07-30 19:00 UTC, bwoodsend approved these changes

2023-07-31 10:37 UTC, keraprogress commented
```
Run flake8 -v
flake8.checker            MainProcess    169 INFO     Making checkers
flake8.main.application   MainProcess   1306 INFO     Finished running
flake8.main.application   MainProcess   1307 INFO     Reporting errors
flake8.main.application   MainProcess   1310 INFO     Found a total of 58 violations and reported 1
./src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pylint.py:54:99: E231 missing whitespace after ','
Error: Process completed with exit code 1.
```
This seems like a pylint bug. These are the lines in hook-pylint.py that pylint doesn't like:
```py
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, is_module_or_submodule,\
    get_module_file_attribute
```

2023-07-31 10:43 UTC, rokm commented
> This seems like a flake8 bug. These are the lines in hook-pylint.py that flake8 doesn't like:

Indeed, and this seems to have been changed in `flake8` 6.1.0 that was released two days ago. Not this PR's problem, though.

2023-07-31 10:43 UTC, merged